/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QueriesRouteImport } from './routes/queries'
import { Route as CompetitorsRouteImport } from './routes/competitors'
import { Route as CitationsRouteImport } from './routes/citations'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditIdRouteImport } from './routes/audit.$id'

const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QueriesRoute = QueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsRoute = CompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => rootRouteImport,
} as any)
const CitationsRoute = CitationsRouteImport.update({
  id: '/citations',
  path: '/citations',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIdRoute = AuditIdRouteImport.update({
  id: '/audit/$id',
  path: '/audit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/analytics': typeof AnalyticsRoute
  '/citations': typeof CitationsRoute
  '/competitors': typeof CompetitorsRoute
  '/queries': typeof QueriesRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/audit/$id': typeof AuditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/analytics': typeof AnalyticsRoute
  '/citations': typeof CitationsRoute
  '/competitors': typeof CompetitorsRoute
  '/queries': typeof QueriesRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/audit/$id': typeof AuditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/analytics': typeof AnalyticsRoute
  '/citations': typeof CitationsRoute
  '/competitors': typeof CompetitorsRoute
  '/queries': typeof QueriesRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/audit/$id': typeof AuditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/analytics'
    | '/citations'
    | '/competitors'
    | '/queries'
    | '/settings'
    | '/summary'
    | '/audit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/analytics'
    | '/citations'
    | '/competitors'
    | '/queries'
    | '/settings'
    | '/summary'
    | '/audit/$id'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/analytics'
    | '/citations'
    | '/competitors'
    | '/queries'
    | '/settings'
    | '/summary'
    | '/audit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CitationsRoute: typeof CitationsRoute
  CompetitorsRoute: typeof CompetitorsRoute
  QueriesRoute: typeof QueriesRoute
  SettingsRoute: typeof SettingsRoute
  SummaryRoute: typeof SummaryRoute
  AuditIdRoute: typeof AuditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queries': {
      id: '/queries'
      path: '/queries'
      fullPath: '/queries'
      preLoaderRoute: typeof QueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors': {
      id: '/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof CompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citations': {
      id: '/citations'
      path: '/citations'
      fullPath: '/citations'
      preLoaderRoute: typeof CitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/$id': {
      id: '/audit/$id'
      path: '/audit/$id'
      fullPath: '/audit/$id'
      preLoaderRoute: typeof AuditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  AnalyticsRoute: AnalyticsRoute,
  CitationsRoute: CitationsRoute,
  CompetitorsRoute: CompetitorsRoute,
  QueriesRoute: QueriesRoute,
  SettingsRoute: SettingsRoute,
  SummaryRoute: SummaryRoute,
  AuditIdRoute: AuditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
